import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SocketProvider } from "@/components/providers/SocketProvider";
import { GameStateProvider } from "@/components/providers/GameStateProvider";

import AudioUnlocker from "@/components/game/AudioUnlocker";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>
           <GameStateProvider>
             <AudioUnlocker>
              {children}
             </AudioUnlocker>
           </GameStateProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
